/* eslint-disable perfectionist/sort-objects -- column configuration reads name, then bounds, then default; the wire order is the columns array, which this rule never touches */
import {
  CanAttach,
  FillPattern,
  FixtureCanCombine,
  FixtureType,
  MerchDirection,
  MerchNumber,
  MerchPlacement,
  MerchSize,
  MerchSqueeze,
  MerchStyle,
} from './enums';
import type { PsaPosition } from './position';
import {
  createEnumColumn,
  createFixedValueColumn,
  createFlagColumn,
  createFloatColumn,
  createIntegerColumn,
  createStringColumn,
  FIVE_NINES,
  FOUR_NINES,
  TEN_NINES,
  toPsaRow,
  type Column,
  type PsaDefinition,
} from './psa-definitions';

const fixtureColumns: Array<Column> = [
  createFixedValueColumn({ name: 'RowType', value: 'Fixture' }),
  createEnumColumn({
    name: 'Type',
    enum: FixtureType,
    defaultValue: FixtureType.Shelf,
  }),
  createStringColumn({ name: 'Name', maxLength: 100 }),
  createStringColumn({ name: 'Key', maxLength: 20 }),
  createFloatColumn({
    name: 'X',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Width',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Y',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Height',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Z',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Depth',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({ name: 'Slope', defaultValue: 0, min: -89, max: 89 }),
  createFloatColumn({ name: 'Angle', defaultValue: 0, min: -360, max: 360 }),
  createFloatColumn({ name: 'Roll', defaultValue: 0, min: -89, max: 89 }),
  createIntegerColumn({
    name: 'Color',
    defaultValue: 0,
    min: -1,
    max: 16_777_215,
  }),
  createStringColumn({ name: 'Assembly', maxLength: 100 }),
  createFloatColumn({
    name: 'XSpacing',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'YSpacing',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'XStart',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'YStart',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'WallWidth',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'WallHeight',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'WallDepth',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({ name: 'Curve', defaultValue: 0, min: -360, max: 360 }),
  createFloatColumn({
    name: 'Merch',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFlagColumn({ name: 'CheckOtherFixtures', defaultValue: 1 }),
  createFlagColumn({ name: 'CheckOtherPositions', defaultValue: 1 }),
  createFlagColumn({ name: 'CanObstruct', defaultValue: 1 }),
  createFloatColumn({
    name: 'LeftOverhang',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'RightOverhang',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'LowerOverhang',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'UpperOverhang',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'BackOverhang',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'FrontOverhang',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createEnumColumn({
    name: 'DefaultMerchStyle',
    enum: MerchStyle,
    defaultValue: MerchStyle.Default,
  }),
  createFloatColumn({
    name: 'DividerWidth',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'DividerHeight',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'DividerDepth',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createEnumColumn({
    name: 'CanCombine',
    enum: FixtureCanCombine,
    defaultValue: FixtureCanCombine.No,
  }),
  createFloatColumn({
    name: 'GrilleHeight',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'NotchOffset',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'XSpacing2',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'XStart2',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'PegDrop',
    defaultValue: 0,
    min: 0,
    max: FOUR_NINES,
  }),
  createFloatColumn({
    name: 'PegGapX',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'PegGapY',
    defaultValue: 0,
    min: 0,
    max: TEN_NINES,
  }),
  createStringColumn({ name: 'PrimaryFixtureLabelFormatName', maxLength: 100 }),
  createStringColumn({
    name: 'SecondaryFixtureLabelFormatName',
    maxLength: 100,
  }),
  createStringColumn({ name: 'ShapeID', maxLength: 50 }),
  createStringColumn({ name: 'BitmapID', maxLength: 260 }),
  createIntegerColumn({
    name: 'MerchXMin',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchXMax',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchXUprights',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchXCaps',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createEnumColumn({
    name: 'MerchXPlacement',
    enum: MerchPlacement,
    defaultValue: MerchPlacement.Spread,
  }),
  createEnumColumn({
    name: 'MerchXNumber',
    enum: MerchNumber,
    defaultValue: MerchNumber.Default,
  }),
  createEnumColumn({
    name: 'MerchXSize',
    enum: MerchSize,
    defaultValue: MerchSize.Default,
  }),
  createEnumColumn({
    name: 'MerchXDirection',
    enum: MerchDirection,
    defaultValue: MerchDirection.Default,
  }),
  createEnumColumn({
    name: 'MerchXSqueeze',
    enum: MerchSqueeze,
    defaultValue: MerchSqueeze.Default,
  }),
  createIntegerColumn({
    name: 'MerchYMin',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchYMax',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchYUprights',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchYCaps',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createEnumColumn({
    name: 'MerchYPlacement',
    enum: MerchPlacement,
    defaultValue: MerchPlacement.Default,
  }),
  createEnumColumn({
    name: 'MerchYNumber',
    enum: MerchNumber,
    defaultValue: MerchNumber.Default,
  }),
  createEnumColumn({
    name: 'MerchYSize',
    enum: MerchSize,
    defaultValue: MerchSize.Default,
  }),
  createEnumColumn({
    name: 'MerchYDirection',
    enum: MerchDirection,
    defaultValue: MerchDirection.Default,
  }),
  createEnumColumn({
    name: 'MerchYSqueeze',
    enum: MerchSqueeze,
    defaultValue: MerchSqueeze.Default,
  }),
  createIntegerColumn({
    name: 'MerchZMin',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchZMax',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchZUprights',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchZCaps',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createEnumColumn({
    name: 'MerchZPlacement',
    enum: MerchPlacement,
    defaultValue: MerchPlacement.Default,
  }),
  createEnumColumn({
    name: 'MerchZNumber',
    enum: MerchNumber,
    defaultValue: MerchNumber.Default,
  }),
  createEnumColumn({
    name: 'MerchZSize',
    enum: MerchSize,
    defaultValue: MerchSize.Default,
  }),
  createEnumColumn({
    name: 'MerchZDirection',
    enum: MerchDirection,
    defaultValue: MerchDirection.Default,
  }),
  createEnumColumn({
    name: 'MerchZSqueeze',
    enum: MerchSqueeze,
    defaultValue: MerchSqueeze.Default,
  }),
  createStringColumn({ name: 'Desc1', maxLength: 1000 }),
  createStringColumn({ name: 'Desc2', maxLength: 1000 }),
  createStringColumn({ name: 'Desc3', maxLength: 1000 }),
  createStringColumn({ name: 'Desc4', maxLength: 1000 }),
  createStringColumn({ name: 'Desc5', maxLength: 1000 }),
  createStringColumn({ name: 'Desc6', maxLength: 1000 }),
  createStringColumn({ name: 'Desc7', maxLength: 1000 }),
  createStringColumn({ name: 'Desc8', maxLength: 1000 }),
  createStringColumn({ name: 'Desc9', maxLength: 1000 }),
  createStringColumn({ name: 'Desc10', maxLength: 1000 }),
  createStringColumn({ name: 'Desc11', maxLength: 1000 }),
  createStringColumn({ name: 'Desc12', maxLength: 1000 }),
  createStringColumn({ name: 'Desc13', maxLength: 1000 }),
  createStringColumn({ name: 'Desc14', maxLength: 1000 }),
  createStringColumn({ name: 'Desc15', maxLength: 1000 }),
  createStringColumn({ name: 'Desc16', maxLength: 1000 }),
  createStringColumn({ name: 'Desc17', maxLength: 1000 }),
  createStringColumn({ name: 'Desc18', maxLength: 1000 }),
  createStringColumn({ name: 'Desc19', maxLength: 1000 }),
  createStringColumn({ name: 'Desc20', maxLength: 1000 }),
  createStringColumn({ name: 'Desc21', maxLength: 1000 }),
  createStringColumn({ name: 'Desc22', maxLength: 1000 }),
  createStringColumn({ name: 'Desc23', maxLength: 1000 }),
  createStringColumn({ name: 'Desc24', maxLength: 1000 }),
  createStringColumn({ name: 'Desc25', maxLength: 1000 }),
  createStringColumn({ name: 'Desc26', maxLength: 1000 }),
  createStringColumn({ name: 'Desc27', maxLength: 1000 }),
  createStringColumn({ name: 'Desc28', maxLength: 1000 }),
  createStringColumn({ name: 'Desc29', maxLength: 1000 }),
  createStringColumn({ name: 'Desc30', maxLength: 1000 }),
  createIntegerColumn({
    name: 'Value1',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value2',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value3',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value4',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value5',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value6',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value7',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value8',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value9',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value10',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value11',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value12',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value13',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value14',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value15',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value16',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value17',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value18',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value19',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value20',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value21',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value22',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value23',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value24',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value25',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value26',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value27',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value28',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value29',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createIntegerColumn({
    name: 'Value30',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFlagColumn({ name: 'Flag1', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag2', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag3', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag4', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag5', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag6', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag7', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag8', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag9', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag10', defaultValue: 0 }),
  createIntegerColumn({
    name: 'LocationID',
    defaultValue: -1,
    min: -1,
    max: FIVE_NINES,
  }),
  createEnumColumn({
    name: 'FillPattern',
    enum: FillPattern,
    defaultValue: FillPattern.Solid,
  }),
  createStringColumn({ name: 'ModelFilename', maxLength: 260 }),
  createFloatColumn({
    name: 'WeightCapacity',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFixedValueColumn({ name: 'Changed', value: 0 }),
  createFlagColumn({ name: 'DividerAtStart', defaultValue: 1 }),
  createFlagColumn({ name: 'DividerAtEnd', defaultValue: 0 }),
  createFlagColumn({ name: 'DividersBetweenFacings', defaultValue: 0 }),
  createFloatColumn({ name: 'Transparency', defaultValue: 0, min: 0, max: 1 }),
  createFlagColumn({ name: 'HideIfPrinting', defaultValue: 0 }),
  createStringColumn({ name: 'ProductAssociation', maxLength: 50 }),
  createStringColumn({ name: 'PartID', maxLength: 50 }),
  createFlagColumn({ name: 'HideViewDimensions', defaultValue: 0 }),
  createStringColumn({ name: 'GLN', maxLength: 17 }),
  createStringColumn({ name: 'CustomData', maxLength: 10_000 }),
  createEnumColumn({
    name: 'CanAttach',
    enum: CanAttach,
    defaultValue: CanAttach.No,
  }),
  createStringColumn({ name: 'AttachedToFixture', maxLength: 100 }),
  createFlagColumn({ name: 'IsAttached', defaultValue: 0 }),
  createIntegerColumn({
    name: 'RankX',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'RankY',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'RankZ',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createStringColumn({ name: 'FixtureGUID', maxLength: 36 }),
];

export type FixtureData = {
  bay?: number;
  id?: string;
  locationId?: number;
  name?: string;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
};

export type PsaFixture = PsaDefinition<typeof fixtureColumns> & {
  positions?: Array<PsaPosition>;
};

export const toPsaFixture = (data: PsaFixture) =>
  toPsaRow(data, fixtureColumns);
