/* eslint-disable perfectionist/sort-objects -- column configuration reads name, then bounds, then default; the wire order is the columns array, which this rule never touches */
import { MerchStyle, Orientation } from './enums';
import {
  createEnumColumn,
  createFixedValueColumn,
  createFlagColumn,
  createFloatColumn,
  createIntegerColumn,
  createStringColumn,
  FIVE_NINES,
  FOUR_NINES,
  SEVEN_NINES,
  SIX_NINES,
  TEN_NINES,
  toPsaRow,
  type Column,
  type PsaDefinition,
} from './psa-definitions';

const performanceColumns: Array<Column> = [
  createFixedValueColumn({ name: 'Type', value: 'Performance' }),
  createStringColumn({ name: 'UPC', maxLength: 20 }),
  createStringColumn({ name: 'ID', maxLength: 20 }),
  createStringColumn({ name: 'Key', maxLength: 20 }),
  createFloatColumn({
    name: 'Price',
    defaultValue: 0,
    min: -1,
    max: SEVEN_NINES,
  }),
  createFloatColumn({
    name: 'CaseCost',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createIntegerColumn({ name: 'TaxCode', defaultValue: 0, min: -1, max: 100 }),
  createFloatColumn({
    name: 'UnitMovement',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({ name: 'Share', defaultValue: 0, min: -1, max: 100 }),
  createFloatColumn({
    name: 'CombinedPerformanceIndex',
    defaultValue: 0,
    min: -SIX_NINES,
    max: SIX_NINES,
  }),
  createStringColumn({ name: 'Desc1', maxLength: 1000 }),
  createStringColumn({ name: 'Desc2', maxLength: 1000 }),
  createStringColumn({ name: 'Desc3', maxLength: 1000 }),
  createStringColumn({ name: 'Desc4', maxLength: 1000 }),
  createStringColumn({ name: 'Desc5', maxLength: 1000 }),
  createStringColumn({ name: 'Desc6', maxLength: 1000 }),
  createStringColumn({ name: 'Desc7', maxLength: 1000 }),
  createStringColumn({ name: 'Desc8', maxLength: 1000 }),
  createStringColumn({ name: 'Desc9', maxLength: 1000 }),
  createStringColumn({ name: 'Desc10', maxLength: 1000 }),
  createFloatColumn({
    name: 'Value1',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value2',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value3',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value4',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value5',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value6',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value7',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value8',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value9',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value10',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFlagColumn({ name: 'Flag1', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag2', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag3', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag4', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag5', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag6', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag7', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag8', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag9', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag10', defaultValue: 0 }),
  createFixedValueColumn({ name: 'Changed', value: 0 }),
  createStringColumn({ name: 'Desc11', maxLength: 1000 }),
  createStringColumn({ name: 'Desc12', maxLength: 1000 }),
  createStringColumn({ name: 'Desc13', maxLength: 1000 }),
  createStringColumn({ name: 'Desc14', maxLength: 1000 }),
  createStringColumn({ name: 'Desc15', maxLength: 1000 }),
  createStringColumn({ name: 'Desc16', maxLength: 1000 }),
  createStringColumn({ name: 'Desc17', maxLength: 1000 }),
  createStringColumn({ name: 'Desc18', maxLength: 1000 }),
  createStringColumn({ name: 'Desc19', maxLength: 1000 }),
  createStringColumn({ name: 'Desc20', maxLength: 1000 }),
  createStringColumn({ name: 'Desc21', maxLength: 1000 }),
  createStringColumn({ name: 'Desc22', maxLength: 1000 }),
  createStringColumn({ name: 'Desc23', maxLength: 1000 }),
  createStringColumn({ name: 'Desc24', maxLength: 1000 }),
  createStringColumn({ name: 'Desc25', maxLength: 1000 }),
  createStringColumn({ name: 'Desc26', maxLength: 1000 }),
  createStringColumn({ name: 'Desc27', maxLength: 1000 }),
  createStringColumn({ name: 'Desc28', maxLength: 1000 }),
  createStringColumn({ name: 'Desc29', maxLength: 1000 }),
  createStringColumn({ name: 'Desc30', maxLength: 1000 }),
  createFloatColumn({
    name: 'Value11',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value12',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value13',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value14',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value15',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value16',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value17',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value18',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value19',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),

  createFloatColumn({
    name: 'Value20',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value21',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value22',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value23',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value24',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value25',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value26',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value27',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value28',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value29',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value30',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'CaseMultiple',
    defaultValue: 0,
    min: 0,
    max: FIVE_NINES,
  }),
  createFloatColumn({ name: 'DaysSupply', defaultValue: 0, min: 0, max: 365 }),
  createFloatColumn({
    name: 'PeakSafetyFactor',
    defaultValue: -0.01,
    min: -0.01,
    max: 100,
  }),
  createFloatColumn({
    name: 'BackroomStock',
    defaultValue: -0.01,
    min: -0.01,
    max: 1,
  }),
  createIntegerColumn({
    name: 'MinimumUnits',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MaximumUnits',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createStringColumn({ name: 'DeliverySchedule', maxLength: 50 }),
  createIntegerColumn({
    name: 'ReplenishmentMin',
    defaultValue: 0,
    min: 0,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'ReplenishmentMax',
    defaultValue: 0,
    min: 0,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'AssortmentRank',
    defaultValue: 0,
    min: 0,
    max: FIVE_NINES,
  }),
  createIntegerColumn({
    name: 'RecommendedFacings',
    defaultValue: 0,
    min: -1,
    max: FIVE_NINES,
  }),
  createStringColumn({ name: 'AssortmentStrategy', maxLength: 50 }),
  createStringColumn({ name: 'AssortmentTactic', maxLength: 50 }),
  createStringColumn({ name: 'AssortmentReason', maxLength: 260 }),
  createStringColumn({ name: 'AssortmentAction', maxLength: 50 }),
  createStringColumn({ name: 'PartID', maxLength: 50 }),
  createStringColumn({ name: 'ClusterName', maxLength: 100 }),
  createIntegerColumn({
    name: 'TargetDistributionStores',
    defaultValue: 0,
    min: 0,
    max: FIVE_NINES,
  }),
  createFloatColumn({
    name: 'TargetDistribution',
    defaultValue: 0,
    min: 0,
    max: 1,
  }),
  createStringColumn({ name: 'AssortmentNote', maxLength: 1000 }),
  createStringColumn({ name: 'Desc31', maxLength: 1000 }),
  createStringColumn({ name: 'Desc32', maxLength: 1000 }),
  createStringColumn({ name: 'Desc33', maxLength: 1000 }),
  createStringColumn({ name: 'Desc34', maxLength: 1000 }),
  createStringColumn({ name: 'Desc35', maxLength: 1000 }),
  createStringColumn({ name: 'Desc36', maxLength: 1000 }),
  createStringColumn({ name: 'Desc37', maxLength: 1000 }),
  createStringColumn({ name: 'Desc38', maxLength: 1000 }),
  createStringColumn({ name: 'Desc39', maxLength: 1000 }),
  createStringColumn({ name: 'Desc40', maxLength: 1000 }),
  createStringColumn({ name: 'Desc41', maxLength: 1000 }),
  createStringColumn({ name: 'Desc42', maxLength: 1000 }),
  createStringColumn({ name: 'Desc43', maxLength: 1000 }),
  createStringColumn({ name: 'Desc44', maxLength: 1000 }),
  createStringColumn({ name: 'Desc45', maxLength: 1000 }),
  createStringColumn({ name: 'Desc46', maxLength: 1000 }),
  createStringColumn({ name: 'Desc47', maxLength: 1000 }),
  createStringColumn({ name: 'Desc48', maxLength: 1000 }),
  createStringColumn({ name: 'Desc49', maxLength: 1000 }),
  createStringColumn({ name: 'Desc50', maxLength: 1000 }),
  createFloatColumn({
    name: 'Value31',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value32',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value33',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value34',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value35',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value36',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value37',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value38',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value39',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value40',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value41',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value42',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value43',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value44',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value45',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value46',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value47',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value48',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value49',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value50',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createStringColumn({ name: 'CustomData', maxLength: 10_000 }),
  createEnumColumn({
    name: 'RecommendedOrientation',
    enum: Orientation,
    defaultValue: Orientation.Default,
  }),
  createEnumColumn({
    name: 'RecommendedMerchStyle',
    enum: MerchStyle,
    defaultValue: MerchStyle.Default,
  }),
  createFlagColumn({ name: 'IgnoreRecommendations', defaultValue: 0 }),
  createIntegerColumn({
    name: 'Priority',
    defaultValue: 0,
    min: 0,
    max: FOUR_NINES,
  }),
  createStringColumn({ name: 'PriorityDesc', maxLength: 100 }),
  createFlagColumn({ name: 'ForceList', defaultValue: 0 }),
  createStringColumn({ name: 'PGReasons', maxLength: 1000 }),
  createFloatColumn({
    name: 'PGMaxStageReduce',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'PGMaxStageFillOut',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
];

export type PsaPerformance = PsaDefinition<typeof performanceColumns>;

export const toPsaPerformance = (data: PsaPerformance) =>
  toPsaRow(data, performanceColumns);
