/* eslint-disable perfectionist/sort-objects -- column configuration reads name, then bounds, then default; the wire order is the columns array, which this rule never touches */
import {
  CanSplit,
  FillPattern,
  MerchDirection,
  MerchNumber,
  MerchPlacement,
  MerchSize,
  MerchSqueeze,
  PGType,
  SourceFileType,
  Status,
  TrafficFlow,
} from './enums';
import type { PsaFixture } from './fixture';
import {
  createBooleanColumn,
  createEnumColumn,
  createFixedValueColumn,
  createFlagColumn,
  createFloatColumn,
  createIntegerColumn,
  createStringColumn,
  EIGHT_NINES,
  FIVE_NINES,
  FOUR_NINES,
  SEVEN_NINES,
  SIX_NINES,
  TEN_NINES,
  toPsaRow,
  type Column,
  type PsaDefinition,
} from './psa-definitions';
import type { PsaSegment } from './segment';

const planogramColumns: Array<Column> = [
  createFixedValueColumn({ name: 'Type', value: 'Planogram' }),
  createStringColumn({ name: 'Name', maxLength: 100 }),
  createStringColumn({ name: 'Key', maxLength: 20 }),
  createFloatColumn({
    name: 'Width',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Height',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Depth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFixedValueColumn({
    name: 'Color',
    value: 16_777_215,
  }),
  createFloatColumn({
    name: 'BackDepth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createBooleanColumn({ name: 'DrawBack', defaultValue: true }),
  createFloatColumn({
    name: 'BaseWidth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'BaseHeight',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'BaseDepth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 50,
  }),
  createFlagColumn({ name: 'DrawBase', defaultValue: 1 }),
  createIntegerColumn({
    name: 'BaseColor',
    min: -1,
    max: 16_777_215,
    defaultValue: 16_777_088,
  }),
  createFlagColumn({ name: 'DrawNotches', defaultValue: 0 }),
  createFloatColumn({
    name: 'NotchOffset',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'NotchSpacing',
    min: 0,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createFlagColumn({ name: 'DoubleNotches', defaultValue: 0 }),
  createIntegerColumn({
    name: 'NotchColor',
    min: -1,
    max: 16_777_215,
    defaultValue: 0,
  }),
  createFlagColumn({ name: 'NotchMarks', defaultValue: 0 }),
  createFlagColumn({ name: 'DrawPegs', defaultValue: 0 }),
  createFlagColumn({ name: 'DrawPegholes', defaultValue: 0 }),
  createEnumColumn({
    name: 'TrafficFlow',
    enum: TrafficFlow,
    defaultValue: TrafficFlow.NA,
  }),
  createFlagColumn({ name: 'AutoCreated', defaultValue: 0 }),
  createStringColumn({ name: 'ShapeID', maxLength: 50 }),
  createStringColumn({ name: 'BitmapID', maxLength: 260 }),
  createIntegerColumn({
    name: 'MerchXMin',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchXMax',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchXUprights',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchXCaps',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createEnumColumn({
    name: 'MerchXPlacement',
    enum: MerchPlacement,
    defaultValue: MerchPlacement.Default,
  }),
  createEnumColumn({
    name: 'MerchXNumber',
    enum: MerchNumber,
    defaultValue: MerchNumber.Default,
  }),
  createEnumColumn({
    name: 'MerchXSize',
    enum: MerchSize,
    defaultValue: MerchSize.Default,
  }),
  createEnumColumn({
    name: 'MerchXDirection',
    enum: MerchDirection,
    defaultValue: MerchDirection.Default,
  }),
  createEnumColumn({
    name: 'MerchXSqueeze',
    enum: MerchSqueeze,
    defaultValue: MerchSqueeze.Default,
  }),
  createIntegerColumn({
    name: 'MerchYMin',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchYMax',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchYUprights',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchYCaps',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createEnumColumn({
    name: 'MerchYPlacement',
    enum: MerchPlacement,
    defaultValue: MerchPlacement.Default,
  }),
  createEnumColumn({
    name: 'MerchYNumber',
    enum: MerchNumber,
    defaultValue: MerchNumber.Default,
  }),
  createEnumColumn({
    name: 'MerchYSize',
    enum: MerchSize,
    defaultValue: MerchSize.Default,
  }),
  createEnumColumn({
    name: 'MerchYDirection',
    enum: MerchDirection,
    defaultValue: MerchDirection.Default,
  }),
  createEnumColumn({
    name: 'MerchYSqueeze',
    enum: MerchSqueeze,
    defaultValue: MerchSqueeze.Default,
  }),
  createIntegerColumn({
    name: 'MerchZMin',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchZMax',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchZUprights',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchZCaps',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createEnumColumn({
    name: 'MerchZPlacement',
    enum: MerchPlacement,
    defaultValue: MerchPlacement.Default,
  }),
  createEnumColumn({
    name: 'MerchZNumber',
    enum: MerchNumber,
    defaultValue: MerchNumber.Default,
  }),
  createEnumColumn({
    name: 'MerchZSize',
    enum: MerchSize,
    defaultValue: MerchSize.Default,
  }),
  createEnumColumn({
    name: 'MerchZDirection',
    enum: MerchDirection,
    defaultValue: MerchDirection.Default,
  }),
  createEnumColumn({
    name: 'MerchZSqueeze',
    enum: MerchSqueeze,
    defaultValue: MerchSqueeze.Default,
  }),
  createFixedValueColumn({ name: 'CombinedPerformanceIndex', value: '' }),
  createIntegerColumn({
    name: 'NumberOfStores',
    min: 1,
    max: FOUR_NINES,
    defaultValue: 1,
  }),
  createFloatColumn({
    name: 'NotchWidth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createStringColumn({
    name: 'Desc1',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc2',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc3',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc4',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc5',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc6',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc7',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc8',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc9',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc10',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc11',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc12',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc13',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc14',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc15',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc16',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc17',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc18',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc19',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc20',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc21',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc22',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc23',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc24',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc25',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc26',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc27',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc28',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc29',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc30',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc31',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc32',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc33',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc34',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc35',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc36',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc37',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc38',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc39',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc40',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc41',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc42',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc43',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc44',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc45',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc46',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc47',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc48',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc49',
    maxLength: 1000,
  }),
  createStringColumn({
    name: 'Desc50',
    maxLength: 1000,
  }),
  createFloatColumn({
    name: 'Value1',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value2',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value3',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value4',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value5',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value6',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value7',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value8',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value9',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value10',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value11',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value12',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value13',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value14',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value15',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value16',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value17',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value18',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value19',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value20',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value21',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value22',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value23',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value24',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value25',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value26',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value27',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value28',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value29',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value30',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value31',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value32',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value33',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value34',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value35',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value36',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value37',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value38',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value39',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value40',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value41',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value42',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value43',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value44',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value45',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value46',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value47',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value48',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value49',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value50',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFlagColumn({ name: 'Flag1', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag2', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag3', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag4', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag5', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag6', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag7', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag8', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag9', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag10', defaultValue: 0 }),
  createEnumColumn({
    name: 'FillPattern',
    enum: FillPattern,
    defaultValue: FillPattern.Solid,
  }),
  createStringColumn({ name: 'SegmentsToPrint', maxLength: 1000 }),
  createStringColumn({ name: 'FileName', maxLength: 260 }),
  createFixedValueColumn({ name: 'Changed', value: 0 }),
  createStringColumn({ name: 'LayoutFileName', maxLength: 13_000 }),
  createStringColumn({
    name: 'Notes',
    maxLength: 1_048_575,
    defaultValue: 'Exported from Vazen',
  }),
  createIntegerColumn({
    name: 'DBKey1',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey2',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey3',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey4',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey5',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey6',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey7',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey8',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey9',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey10',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createEnumColumn({
    name: 'SourceFileType',
    enum: SourceFileType,
    defaultValue: SourceFileType.SpacePlanning,
  }),
  createEnumColumn({
    name: 'Status1',
    enum: Status,
    defaultValue: Status.Default,
  }),
  createEnumColumn({
    name: 'Status2',
    enum: Status,
    defaultValue: Status.Default,
  }),
  createEnumColumn({
    name: 'Status3',
    enum: Status,
    defaultValue: Status.Default,
  }),
  createIntegerColumn({
    name: 'DateCreated',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DateModified',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DatePending',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DateEffective',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DateFinished',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Date1',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Date2',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Date3',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createStringColumn({ name: 'CreatedBy', maxLength: 100 }),
  createStringColumn({ name: 'ModifiedBy', maxLength: 100 }),
  createStringColumn({ name: 'FloorBitmapID', maxLength: 260 }),
  createFloatColumn({
    name: 'DoorTransparency',
    min: 0,
    max: 1,
    defaultValue: 0.5,
  }),
  createFloatColumn({
    name: 'FloorTileWidth',
    min: 0,
    max: SIX_NINES,
    defaultValue: 12,
  }),
  createFloatColumn({
    name: 'FloorTileDepth',
    min: 0,
    max: SIX_NINES,
    defaultValue: 12,
  }),
  createFlagColumn({ name: 'InventoryModelManual', defaultValue: 0 }),
  createFlagColumn({ name: 'InventoryModelCaseMultiple', defaultValue: 0 }),
  createFlagColumn({ name: 'InventoryModelDaysSupply', defaultValue: 0 }),
  createFlagColumn({ name: 'InventoryModelPeak', defaultValue: 0 }),
  createFlagColumn({ name: 'InventoryModelMinUnits', defaultValue: 0 }),
  createFlagColumn({ name: 'InventoryModelMaxUnits', defaultValue: 0 }),
  createFloatColumn({
    name: 'CaseMultiple',
    min: 0,
    max: FIVE_NINES,
    defaultValue: 1.5,
  }),
  createFloatColumn({
    name: 'DaysSupply',
    min: 0.1,
    max: 365,
    defaultValue: 1,
  }),
  createIntegerColumn({
    name: 'DemandCycleLength',
    min: 1,
    max: 7,
    defaultValue: 1,
  }),
  createFloatColumn({
    name: 'PeakSafetyFactor',
    min: 0,
    max: 100,
    defaultValue: 1,
  }),
  createFloatColumn({ name: 'BackroomStock', min: 0, max: 1, defaultValue: 0 }),
  createFloatColumn({
    name: 'Demand1',
    min: 0,
    max: EIGHT_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Demand2',
    min: 0,
    max: EIGHT_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Demand3',
    min: 0,
    max: EIGHT_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Demand4',
    min: 0,
    max: EIGHT_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Demand5',
    min: 0,
    max: EIGHT_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Demand6',
    min: 0,
    max: EIGHT_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Demand7',
    min: 0,
    max: EIGHT_NINES,
    defaultValue: 0,
  }),
  createStringColumn({ name: 'DeliverySchedule', maxLength: 50 }),
  createStringColumn({ name: 'ID', maxLength: 16 }),
  createStringColumn({ name: 'Department', maxLength: 1000 }),
  createStringColumn({ name: 'PartID', maxLength: 50 }),
  createStringColumn({ name: 'GLN', maxLength: 17 }),
  createStringColumn({ name: 'CustomData', maxLength: 1000 }),
  createStringColumn({ name: 'PlanogramGUID', maxLength: 36 }),
  createStringColumn({ name: 'DBGUID', maxLength: 36 }),
  createStringColumn({ name: 'AbbrevName', maxLength: 20 }),
  createStringColumn({ name: 'Category', maxLength: 1000 }),
  createStringColumn({ name: 'Subcategory', maxLength: 1000 }),
  createIntegerColumn({
    name: 'Source',
    min: -FOUR_NINES,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createStringColumn({ name: 'AllocationGroup', maxLength: 100 }),
  createIntegerColumn({
    name: 'AllocationSequence',
    min: 0,
    max: FIVE_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'AllocationTargetMin',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'AllocationTargetMax',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),

  createFixedValueColumn({ name: 'CanSegment', value: 0 }), //obsolete
  createEnumColumn({
    name: 'CanSplit',
    enum: CanSplit,
    defaultValue: CanSplit.Default,
  }),
  createIntegerColumn({
    name: 'PGStatus',
    min: -SEVEN_NINES,
    max: SEVEN_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'PGScorePercent',
    min: -SEVEN_NINES,
    max: SEVEN_NINES,
    defaultValue: -1,
  }),
  createStringColumn({ name: 'PGScoreNote', maxLength: 255 }),
  createIntegerColumn({
    name: 'PGWarningsCount',
    min: -SEVEN_NINES,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'PGErrorsCount',
    min: -SEVEN_NINES,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFixedValueColumn({ name: 'PGActionList', value: '' }), //obsolete
  createFloatColumn({
    name: 'PGMaxStageReduce',
    min: -SEVEN_NINES,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'PGMaxStageFillOut',
    min: -SEVEN_NINES,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createEnumColumn({
    name: 'PGType',
    enum: PGType,
    defaultValue: PGType.Default,
  }),
  createStringColumn({ name: 'ModelFilename', maxLength: 260 }),
  createIntegerColumn({
    name: 'DBFamilyKey',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBReplaceKey',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBVersionKey',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBParentPGAuxTemplateKey',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBParentPGSourceKey',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBParentPGTemplateKey',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBPGTimeDone',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createStringColumn({ name: 'PGServerName', maxLength: 255 }),
  createIntegerColumn({
    name: 'PRStatus',
    min: -SEVEN_NINES,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'MovementPeriod',
    min: 0,
    max: 365,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'AllocationSectionSplits',
    min: 0,
    max: FIVE_NINES,
    defaultValue: 1,
  }),
  createIntegerColumn({
    name: 'AllocationSectionSplitsMin',
    min: 0,
    max: FIVE_NINES,
    defaultValue: 1,
  }),
  createIntegerColumn({
    name: 'AllocationPriority',
    min: 0,
    max: FIVE_NINES,
    defaultValue: 0,
  }),
  createFixedValueColumn({ name: 'Checksum1', value: '' }),
  createFixedValueColumn({ name: 'Checksum2', value: '' }),
  createFixedValueColumn({ name: 'Checksum3', value: '' }),
  createFixedValueColumn({ name: 'Checksum4', value: '' }),
  createFixedValueColumn({ name: 'Checksum5', value: '' }),
  createFlagColumn({ name: 'UseAsSubplanogram', defaultValue: 0 }),
];

export type PsaPlanogram = PsaDefinition<typeof planogramColumns> & {
  fixtures?: Array<PsaFixture>;
  segments?: Array<PsaSegment>;
};

export const toPsaPlanogram = (data: PsaPlanogram) =>
  toPsaRow(data, planogramColumns);
