/* eslint-disable perfectionist/sort-objects -- column configuration reads name, then bounds, then default; the wire order is the columns array, which this rule never touches */
import {
  AutomaticModel,
  MerchDirection,
  MerchNumber,
  MerchPlacement,
  MerchSize,
  MerchSqueeze,
  MerchStyle,
  Orientation,
} from './enums';
import {
  createEnumColumn,
  createFixedValueColumn,
  createFlagColumn,
  createFloatColumn,
  createIntegerColumn,
  createStringColumn,
  FIVE_NINES,
  FOUR_NINES,
  SEVEN_NINES,
  TEN_NINES,
  toPsaRow,
  type Column,
  type PsaDefinition,
} from './psa-definitions';

export type PositionData = {
  facingsHigh: number;
  facingsWide: number;
  gtin: string | undefined;
  id: string | undefined;
  locationId: number;
  rankX: number;
  secondaryId: string | undefined;
  x: number;
  y: number;
  width: number;
  height: number;
  depth: number;
};

const positionColumns: Array<Column> = [
  createFixedValueColumn({ name: 'Type', value: 'Position' }),
  createStringColumn({ name: 'UPC', maxLength: 20 }),
  createStringColumn({ name: 'ID', maxLength: 20 }),
  createStringColumn({ name: 'Key', maxLength: 20 }),
  createFloatColumn({
    name: 'X',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Width',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createFloatColumn({
    name: 'Y',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Height',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createFloatColumn({
    name: 'Z',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Depth',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createFloatColumn({ name: 'Slope', defaultValue: 0, min: -89, max: 89 }),
  createFloatColumn({ name: 'Angle', defaultValue: 0, min: -360, max: 360 }),
  createFloatColumn({ name: 'Roll', defaultValue: 0, min: -89, max: 89 }),
  createEnumColumn({
    name: 'MerchStyle',
    enum: MerchStyle,
    defaultValue: MerchStyle.Unit,
  }),
  createIntegerColumn({
    name: 'HFacings',
    defaultValue: 1,
    min: 1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'VFacings',
    defaultValue: 1,
    min: 1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'DFacings',
    defaultValue: 1,
    min: 1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'XCapNum',
    defaultValue: 0,
    min: 0,
    max: FOUR_NINES,
  }),
  createFlagColumn({ name: 'XCapNested', defaultValue: 0 }),
  createFlagColumn({ name: 'XCapReversed', defaultValue: 0 }),
  createEnumColumn({
    name: 'XCapOrientation',
    enum: Orientation,
    defaultValue: Orientation.Side,
  }),
  createIntegerColumn({
    name: 'YCapNum',
    defaultValue: 0,
    min: 0,
    max: FOUR_NINES,
  }),
  createFlagColumn({ name: 'YCapNested', defaultValue: 0 }),
  createFlagColumn({ name: 'YCapReversed', defaultValue: 0 }),
  createEnumColumn({
    name: 'YCapOrientation',
    enum: Orientation,
    defaultValue: Orientation.Top,
  }),
  createIntegerColumn({
    name: 'ZCapNum',
    defaultValue: 0,
    min: 0,
    max: FOUR_NINES,
  }),
  createFlagColumn({ name: 'ZCapNested', defaultValue: 0 }),
  createFlagColumn({ name: 'ZCapReversed', defaultValue: 0 }),
  createEnumColumn({
    name: 'ZCapOrientation',
    enum: Orientation,
    defaultValue: Orientation.Side,
  }),
  createEnumColumn({
    name: 'Orientation',
    enum: Orientation,
    defaultValue: Orientation.Front,
  }),
  createFloatColumn({
    name: 'JumbleWidth',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createFloatColumn({
    name: 'JumbleHeight',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createFloatColumn({
    name: 'JumbleDepth',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createFloatColumn({
    name: 'MerchStyleWidth',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createFloatColumn({
    name: 'MerchStyleHeight',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createFloatColumn({
    name: 'MerchStyleDepth',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createFloatColumn({
    name: 'FullWidth',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createFloatColumn({
    name: 'FullHeight',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createFloatColumn({
    name: 'FullDepth',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createIntegerColumn({
    name: 'XSubUnits',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createIntegerColumn({
    name: 'YSubUnits',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createIntegerColumn({
    name: 'ZSubUnits',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createStringColumn({ name: 'PegID', maxLength: 100 }),
  createIntegerColumn({
    name: 'ManualUnits',
    defaultValue: 1,
    min: 0,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'RankX',
    defaultValue: 1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'RankY',
    defaultValue: 1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'RankZ',
    defaultValue: 1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'PegSpan',
    defaultValue: 0,
    min: 0,
    max: 10,
  }),
  createFlagColumn({ name: 'AlwaysFloat', defaultValue: 0 }),
  createStringColumn({
    name: 'PrimaryPositionLabelFormatName',
    maxLength: 100,
  }),
  createStringColumn({
    name: 'SecondaryPositionLabelFormatName',
    maxLength: 100,
  }),
  createIntegerColumn({
    name: 'MerchXMin',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchXMax',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchXUprights',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchXCaps',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createEnumColumn({
    name: 'MerchXPlacement',
    enum: MerchPlacement,
    defaultValue: MerchPlacement.Spread,
  }),
  createEnumColumn({
    name: 'MerchXNumber',
    enum: MerchNumber,
    defaultValue: MerchNumber.Default,
  }),
  createEnumColumn({
    name: 'MerchXSize',
    enum: MerchSize,
    defaultValue: MerchSize.Default,
  }),
  createEnumColumn({
    name: 'MerchXDirection',
    enum: MerchDirection,
    defaultValue: MerchDirection.Default,
  }),
  createEnumColumn({
    name: 'MerchXSqueeze',
    enum: MerchSqueeze,
    defaultValue: MerchSqueeze.Default,
  }),
  createIntegerColumn({
    name: 'MerchYMin',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchYMax',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchYUprights',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchYCaps',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createEnumColumn({
    name: 'MerchYPlacement',
    enum: MerchPlacement,
    defaultValue: MerchPlacement.Default,
  }),
  createEnumColumn({
    name: 'MerchYNumber',
    enum: MerchNumber,
    defaultValue: MerchNumber.Default,
  }),
  createEnumColumn({
    name: 'MerchYSize',
    enum: MerchSize,
    defaultValue: MerchSize.Default,
  }),
  createEnumColumn({
    name: 'MerchYDirection',
    enum: MerchDirection,
    defaultValue: MerchDirection.Default,
  }),
  createEnumColumn({
    name: 'MerchYSqueeze',
    enum: MerchSqueeze,
    defaultValue: MerchSqueeze.Default,
  }),
  createIntegerColumn({
    name: 'MerchZMin',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchZMax',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchZUprights',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'MerchZCaps',
    defaultValue: -1,
    min: -1,
    max: FOUR_NINES,
  }),
  createEnumColumn({
    name: 'MerchZPlacement',
    enum: MerchPlacement,
    defaultValue: MerchPlacement.Default,
  }),
  createEnumColumn({
    name: 'MerchZNumber',
    enum: MerchNumber,
    defaultValue: MerchNumber.Default,
  }),
  createEnumColumn({
    name: 'MerchZSize',
    enum: MerchSize,
    defaultValue: MerchSize.Default,
  }),
  createEnumColumn({
    name: 'MerchZDirection',
    enum: MerchDirection,
    defaultValue: MerchDirection.Default,
  }),
  createEnumColumn({
    name: 'MerchZSqueeze',
    enum: MerchSqueeze,
    defaultValue: MerchSqueeze.Default,
  }),
  createStringColumn({ name: 'Desc1', maxLength: 1000 }),
  createStringColumn({ name: 'Desc2', maxLength: 1000 }),
  createStringColumn({ name: 'Desc3', maxLength: 1000 }),
  createStringColumn({ name: 'Desc4', maxLength: 1000 }),
  createStringColumn({ name: 'Desc5', maxLength: 1000 }),
  createStringColumn({ name: 'Desc6', maxLength: 1000 }),
  createStringColumn({ name: 'Desc7', maxLength: 1000 }),
  createStringColumn({ name: 'Desc8', maxLength: 1000 }),
  createStringColumn({ name: 'Desc9', maxLength: 1000 }),
  createStringColumn({ name: 'Desc10', maxLength: 1000 }),
  createStringColumn({ name: 'Desc11', maxLength: 1000 }),
  createStringColumn({ name: 'Desc12', maxLength: 1000 }),
  createStringColumn({ name: 'Desc13', maxLength: 1000 }),
  createStringColumn({ name: 'Desc14', maxLength: 1000 }),
  createStringColumn({ name: 'Desc15', maxLength: 1000 }),
  createStringColumn({ name: 'Desc16', maxLength: 1000 }),
  createStringColumn({ name: 'Desc17', maxLength: 1000 }),
  createStringColumn({ name: 'Desc18', maxLength: 1000 }),
  createStringColumn({ name: 'Desc19', maxLength: 1000 }),
  createStringColumn({ name: 'Desc20', maxLength: 1000 }),
  createStringColumn({ name: 'Desc21', maxLength: 1000 }),
  createStringColumn({ name: 'Desc22', maxLength: 1000 }),
  createStringColumn({ name: 'Desc23', maxLength: 1000 }),
  createStringColumn({ name: 'Desc24', maxLength: 1000 }),
  createStringColumn({ name: 'Desc25', maxLength: 1000 }),
  createStringColumn({ name: 'Desc26', maxLength: 1000 }),
  createStringColumn({ name: 'Desc27', maxLength: 1000 }),
  createStringColumn({ name: 'Desc28', maxLength: 1000 }),
  createStringColumn({ name: 'Desc29', maxLength: 1000 }),
  createStringColumn({ name: 'Desc30', maxLength: 1000 }),
  createFloatColumn({
    name: 'Value1',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value2',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value3',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value4',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value5',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value6',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value7',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value8',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value9',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value10',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value11',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value12',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value13',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value14',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value15',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value16',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value17',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value18',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value19',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value20',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value21',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value22',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value23',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value24',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value25',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value26',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value27',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value28',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value29',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFloatColumn({
    name: 'Value30',
    defaultValue: 0,
    min: -TEN_NINES,
    max: TEN_NINES,
  }),
  createFlagColumn({ name: 'Flag1', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag2', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag3', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag4', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag5', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag6', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag7', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag8', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag9', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag10', defaultValue: 0 }),
  createFlagColumn({ name: 'UseTargetSpaceX', defaultValue: 0 }),
  createFlagColumn({ name: 'UseTargetSpaceY', defaultValue: 0 }),
  createFlagColumn({ name: 'UseTargetSpaceZ', defaultValue: 0 }),
  createFloatColumn({
    name: 'TargetSpaceX',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createFloatColumn({
    name: 'TargetSpaceY',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createFloatColumn({
    name: 'TargetSpaceZ',
    defaultValue: 0,
    min: 0,
    max: SEVEN_NINES,
  }),
  createIntegerColumn({
    name: 'LocationID',
    defaultValue: -1,
    min: -1,
    max: FIVE_NINES,
  }),
  createFixedValueColumn({ name: 'Changed', value: 0 }),
  createIntegerColumn({
    name: 'ReplenishmentMin',
    defaultValue: 0,
    min: 0,
    max: FOUR_NINES,
  }),
  createIntegerColumn({
    name: 'ReplenishmentMax',
    defaultValue: 0,
    min: 0,
    max: FOUR_NINES,
  }),
  createStringColumn({ name: 'ShapeID', maxLength: 50 }),
  createStringColumn({ name: 'BitmapIDOverride', maxLength: 260 }),
  createFlagColumn({ name: 'HideIfPrinting', defaultValue: 0 }),
  createStringColumn({ name: 'PartID', maxLength: 50 }),
  createFlagColumn({ name: 'BitmapIDOverrideUnit', defaultValue: 0 }),
  createEnumColumn({
    name: 'AutomaticModel',
    enum: AutomaticModel,
    defaultValue: AutomaticModel.Default,
  }),
  createStringColumn({ name: 'CustomData', maxLength: 10_000 }),
  createFlagColumn({ name: 'XCapWithUnits', defaultValue: 0 }),
  createFlagColumn({ name: 'YCapWithUnits', defaultValue: 0 }),
  createFlagColumn({ name: 'ZCapWithUnits', defaultValue: 0 }),
];

export type PsaPosition = PsaDefinition<typeof positionColumns>;

export const toPsaPosition = (data: PsaPosition) =>
  toPsaRow(data, positionColumns);
