/* eslint-disable perfectionist/sort-objects -- column configuration reads name, then bounds, then default; the wire order is the columns array, which this rule never touches */
import {
  AutomaticModel,
  FillPattern,
  MerchDirection,
  MerchNumber,
  MerchPlacement,
  MerchSize,
  MerchSqueeze,
  MerchStyle,
  ModelFilenameLookup,
  PackageStyle,
  Status,
} from './enums';
import {
  createEnumColumn,
  createFixedValueColumn,
  createFlagColumn,
  createFloatColumn,
  createIntegerColumn,
  createStringColumn,
  FOUR_NINES,
  SEVEN_NINES,
  SIX_NINES,
  TEN_NINES,
  toPsaRow,
  type Column,
  type PsaDefinition,
} from './psa-definitions';

const productColumns: Array<Column> = [
  createFixedValueColumn({ name: 'Type', value: 'Product' }),
  createStringColumn({ name: 'UPC', maxLength: 20 }),
  createStringColumn({ name: 'ID', maxLength: 20 }),
  createStringColumn({ name: 'Name', maxLength: 100 }),
  createStringColumn({ name: 'Key', maxLength: 20 }),
  createFloatColumn({ name: 'Width', min: 0, max: SEVEN_NINES }),
  createFloatColumn({ name: 'Height', min: 0, max: SEVEN_NINES }),
  createFloatColumn({ name: 'Depth', min: 0, max: SEVEN_NINES }),
  createIntegerColumn({
    name: 'Color',
    min: -1,
    max: 16_777_215,
    defaultValue: 0,
  }),
  createStringColumn({ name: 'AbbrevName', maxLength: 20 }),
  createFloatColumn({
    name: 'Size',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createStringColumn({ name: 'UOM', maxLength: 5 }),
  createStringColumn({ name: 'Manufacturer', maxLength: 1000 }),
  createStringColumn({ name: 'Category', maxLength: 1000 }),
  createStringColumn({ name: 'Supplier', maxLength: 1000 }),
  createIntegerColumn({
    name: 'InnerPack',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'XNesting',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'YNesting',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'ZNesting',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({ name: 'Pegholes', min: 0, max: 3, defaultValue: 1 }),
  createFloatColumn({
    name: 'PegholeX',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'PegholeY',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'PegholeWidth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Peghole2X',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Peghole2Y',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Peghole2Width',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Peghole3X',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Peghole3Y',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Peghole3Width',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createEnumColumn({
    name: 'PackageStyle',
    enum: PackageStyle,
    defaultValue: PackageStyle.BoxStandOrHang,
  }),
  createStringColumn({ name: 'PegID', maxLength: 100 }),
  createFloatColumn({
    name: 'FingerSpaceY',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'JumbleFactor',
    min: -1,
    max: 99.99,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'Price',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'CaseCost',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({ name: 'TaxCode', min: 0, max: 10, defaultValue: 1 }),
  createFloatColumn({
    name: 'UnitMovement',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({ name: 'Share', min: 0, max: 100, defaultValue: 0 }),
  createFloatColumn({
    name: 'CaseMultiple',
    min: 0,
    max: SIX_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'DaysSupply',
    min: 0,
    max: SIX_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'CombinedPerformanceIndex',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({ name: 'PegSpan', min: 0, max: 10, defaultValue: 0 }),
  createIntegerColumn({
    name: 'MinimumUnits',
    min: 0,
    max: 9999,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'MaximumUnits',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createStringColumn({ name: 'ShapeID', maxLength: 50 }),
  createStringColumn({ name: 'BitmapIDOverride', maxLength: 260 }),
  createFloatColumn({
    name: 'TrayWidth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'TrayHeight',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'TrayDepth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'TrayNumberWide',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'TrayNumberHigh',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'TrayNumberDeep',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'TrayTotalNumber',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'TrayMaxHigh',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'CaseWidth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'CaseHeight',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'CaseDepth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'CaseNumberWide',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'CaseNumberHigh',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'CaseNumberDeep',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'CaseTotalNumber',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'CaseMaxHigh',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'DisplayWidth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'DisplayHeight',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'DisplayDepth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DisplayNumberWide',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DisplayNumberHigh',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DisplayNumberDeep',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DisplayTotalNumber',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DisplayMaxHigh',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'AlternateWidth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'AlternateHeight',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'AlternateDepth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'AlternateNumberWide',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'AlternateNumberHigh',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'AlternateNumberDeep',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'AlternateTotalNumber',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'AlternateMaxHigh',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'LooseWidth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'LooseHeight',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'LooseDepth',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'LooseNumberWide',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'LooseNumberHigh',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'LooseNumberDeep',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'LooseTotalNumber',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'LooseMaxHigh',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'MerchXMin',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchXMax',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchXUprights',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchXCaps',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createEnumColumn({
    name: 'MerchXPlacement',
    enum: MerchPlacement,
    defaultValue: MerchPlacement.Default,
  }),
  createEnumColumn({
    name: 'MerchXNumber',
    enum: MerchNumber,
    defaultValue: MerchNumber.Default,
  }),
  createEnumColumn({
    name: 'MerchXSize',
    enum: MerchSize,
    defaultValue: MerchSize.Default,
  }),
  createEnumColumn({
    name: 'MerchXDirection',
    enum: MerchDirection,
    defaultValue: MerchDirection.Default,
  }),
  createEnumColumn({
    name: 'MerchXSqueeze',
    enum: MerchSqueeze,
    defaultValue: MerchSqueeze.Default,
  }),
  createIntegerColumn({
    name: 'MerchYMin',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchYMax',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchYUprights',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchYCaps',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createEnumColumn({
    name: 'MerchYPlacement',
    enum: MerchPlacement,
    defaultValue: MerchPlacement.Default,
  }),
  createEnumColumn({
    name: 'MerchYNumber',
    enum: MerchNumber,
    defaultValue: MerchNumber.Default,
  }),
  createEnumColumn({
    name: 'MerchYSize',
    enum: MerchSize,
    defaultValue: MerchSize.Default,
  }),
  createEnumColumn({
    name: 'MerchYDirection',
    enum: MerchDirection,
    defaultValue: MerchDirection.Default,
  }),
  createEnumColumn({
    name: 'MerchYSqueeze',
    enum: MerchSqueeze,
    defaultValue: MerchSqueeze.Default,
  }),
  createIntegerColumn({
    name: 'MerchZMin',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchZMax',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchZUprights',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'MerchZCaps',
    min: -1,
    max: FOUR_NINES,
    defaultValue: -1,
  }),
  createEnumColumn({
    name: 'MerchZPlacement',
    enum: MerchPlacement,
    defaultValue: MerchPlacement.Default,
  }),
  createEnumColumn({
    name: 'MerchZNumber',
    enum: MerchNumber,
    defaultValue: MerchNumber.Default,
  }),
  createEnumColumn({
    name: 'MerchZSize',
    enum: MerchSize,
    defaultValue: MerchSize.Default,
  }),
  createEnumColumn({
    name: 'MerchZDirection',
    enum: MerchDirection,
    defaultValue: MerchDirection.Default,
  }),
  createEnumColumn({
    name: 'MerchZSqueeze',
    enum: MerchSqueeze,
    defaultValue: MerchSqueeze.Default,
  }),
  createIntegerColumn({
    name: 'NumberOfPositions',
    min: 0,
    max: FOUR_NINES,
    defaultValue: 1,
  }),
  createStringColumn({ name: 'Desc1', maxLength: 1000 }),
  createStringColumn({ name: 'Desc2', maxLength: 1000 }),
  createStringColumn({ name: 'Desc3', maxLength: 1000 }),
  createStringColumn({ name: 'Desc4', maxLength: 1000 }),
  createStringColumn({ name: 'Desc5', maxLength: 1000 }),
  createStringColumn({ name: 'Desc6', maxLength: 1000 }),
  createStringColumn({ name: 'Desc7', maxLength: 1000 }),
  createStringColumn({ name: 'Desc8', maxLength: 1000 }),
  createStringColumn({ name: 'Desc9', maxLength: 1000 }),
  createStringColumn({ name: 'Desc10', maxLength: 1000 }),
  createStringColumn({ name: 'Desc11', maxLength: 1000 }),
  createStringColumn({ name: 'Desc12', maxLength: 1000 }),
  createStringColumn({ name: 'Desc13', maxLength: 1000 }),
  createStringColumn({ name: 'Desc14', maxLength: 1000 }),
  createStringColumn({ name: 'Desc15', maxLength: 1000 }),
  createStringColumn({ name: 'Desc16', maxLength: 1000 }),
  createStringColumn({ name: 'Desc17', maxLength: 1000 }),
  createStringColumn({ name: 'Desc18', maxLength: 1000 }),
  createStringColumn({ name: 'Desc19', maxLength: 1000 }),
  createStringColumn({ name: 'Desc20', maxLength: 1000 }),
  createStringColumn({ name: 'Desc21', maxLength: 1000 }),
  createStringColumn({ name: 'Desc22', maxLength: 1000 }),
  createStringColumn({ name: 'Desc23', maxLength: 1000 }),
  createStringColumn({ name: 'Desc24', maxLength: 1000 }),
  createStringColumn({ name: 'Desc25', maxLength: 1000 }),
  createStringColumn({ name: 'Desc26', maxLength: 1000 }),
  createStringColumn({ name: 'Desc27', maxLength: 1000 }),
  createStringColumn({ name: 'Desc28', maxLength: 1000 }),
  createStringColumn({ name: 'Desc29', maxLength: 1000 }),
  createStringColumn({ name: 'Desc30', maxLength: 1000 }),
  createStringColumn({ name: 'Desc31', maxLength: 1000 }),
  createStringColumn({ name: 'Desc32', maxLength: 1000 }),
  createStringColumn({ name: 'Desc33', maxLength: 1000 }),
  createStringColumn({ name: 'Desc34', maxLength: 1000 }),
  createStringColumn({ name: 'Desc35', maxLength: 1000 }),
  createStringColumn({ name: 'Desc36', maxLength: 1000 }),
  createStringColumn({ name: 'Desc37', maxLength: 1000 }),
  createStringColumn({ name: 'Desc38', maxLength: 1000 }),
  createStringColumn({ name: 'Desc39', maxLength: 1000 }),
  createStringColumn({ name: 'Desc40', maxLength: 1000 }),
  createStringColumn({ name: 'Desc41', maxLength: 1000 }),
  createStringColumn({ name: 'Desc42', maxLength: 1000 }),
  createStringColumn({ name: 'Desc43', maxLength: 1000 }),
  createStringColumn({ name: 'Desc44', maxLength: 1000 }),
  createStringColumn({ name: 'Desc45', maxLength: 1000 }),
  createStringColumn({ name: 'Desc46', maxLength: 1000 }),
  createStringColumn({ name: 'Desc47', maxLength: 1000 }),
  createStringColumn({ name: 'Desc48', maxLength: 1000 }),
  createStringColumn({ name: 'Desc49', maxLength: 1000 }),
  createStringColumn({ name: 'Desc50', maxLength: 1000 }),
  createIntegerColumn({
    name: 'Value1',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value2',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value3',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value4',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value5',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value6',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value7',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value8',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value9',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value10',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value11',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value12',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value13',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value14',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value15',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value16',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value17',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value18',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value19',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value20',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value21',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value22',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value23',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value24',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value25',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value26',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value27',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value28',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value29',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value30',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value31',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value32',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value33',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value34',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value35',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value36',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value37',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value38',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value39',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value40',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value41',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value42',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value43',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value44',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value45',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value46',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value47',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value48',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value49',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'Value50',
    min: -TEN_NINES,
    max: TEN_NINES,
    defaultValue: 0,
  }),
  createFlagColumn({ name: 'Flag1', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag2', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag3', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag4', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag5', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag6', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag7', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag8', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag9', defaultValue: 0 }),
  createFlagColumn({ name: 'Flag10', defaultValue: 0 }),
  createFloatColumn({
    name: 'MinimumSqueezeFactorX',
    min: 0.01,
    max: 1,
    defaultValue: 1,
  }),
  createFloatColumn({
    name: 'MinimumSqueezeFactorY',
    min: 0.01,
    max: 1,
    defaultValue: 1,
  }),
  createFloatColumn({
    name: 'MinimumSqueezeFactorZ',
    min: 0.01,
    max: 1,
    defaultValue: 1,
  }),
  createFloatColumn({
    name: 'MaximumSqueezeFactorX',
    min: 1,
    max: 999.99,
    defaultValue: 1,
  }),
  createFloatColumn({
    name: 'MaximumSqueezeFactorY',
    min: 1,
    max: 999.99,
    defaultValue: 1,
  }),
  createFloatColumn({
    name: 'MaximumSqueezeFactorZ',
    min: 1,
    max: 999.99,
    defaultValue: 1,
  }),
  createEnumColumn({
    name: 'FillPattern',
    enum: FillPattern,
    defaultValue: FillPattern.Solid,
  }),
  createStringColumn({ name: 'ModelFilename', maxLength: 260 }),
  createStringColumn({ name: 'Brand', maxLength: 1000 }),
  createStringColumn({ name: 'Subcategory', maxLength: 1000 }),
  createIntegerColumn({
    name: 'Weight',
    min: -SEVEN_NINES,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createStringColumn({ name: 'PlanogramAlias', maxLength: 1000 }),
  createFixedValueColumn({ name: 'Changed', value: 0 }),
  createIntegerColumn({
    name: 'FrontOverhang',
    min: -SEVEN_NINES,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'FingerSpaceX',
    min: 0,
    max: SEVEN_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DBKey1',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey2',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey3',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey4',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey5',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey6',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey7',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey8',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey9',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createIntegerColumn({
    name: 'DBKey10',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createEnumColumn({
    name: 'Status',
    enum: Status,
    defaultValue: Status.Default,
  }),
  createIntegerColumn({
    name: 'DateCreated',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DateModified',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DatePending',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DateEffective',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'DateFinished',
    min: 0,
    max: 401_768,
    defaultValue: 0,
  }),
  createIntegerColumn({ name: 'Date1', min: 0, max: 401_768, defaultValue: 0 }),
  createIntegerColumn({ name: 'Date2', min: 0, max: 401_768, defaultValue: 0 }),
  createIntegerColumn({ name: 'Date3', min: 0, max: 401_768, defaultValue: 0 }),
  createStringColumn({ name: 'CreatedBy', maxLength: 100 }),
  createStringColumn({ name: 'ModifiedBy', maxLength: 100 }),
  createFloatColumn({
    name: 'Transparency',
    min: 0,
    max: 1,
    defaultValue: 0,
  }),
  createFloatColumn({
    name: 'PeakSafetyFactor',
    min: -0.01,
    max: 100,
    defaultValue: -0.01,
  }),
  createFloatColumn({
    name: 'BackroomStock',
    min: -0.01,
    max: 1,
    defaultValue: -0.01,
  }),
  createStringColumn({ name: 'DeliverySchedule', maxLength: 50 }),
  createStringColumn({ name: 'PartID', maxLength: 50 }),
  createFixedValueColumn({ name: 'AuthorityLevel', value: 0 }),
  createFixedValueColumn({ name: 'BitmapIDOverrideUnit', value: 0 }),
  createEnumColumn({
    name: 'ModelFilenameLookup',
    enum: ModelFilenameLookup,
    defaultValue: ModelFilenameLookup.SearchForMerchStyleSpecificModel,
  }),
  createEnumColumn({
    name: 'DefaultMerchStyle',
    enum: MerchStyle,
    defaultValue: MerchStyle.Default,
  }),
  createEnumColumn({
    name: 'AutomaticModel',
    enum: AutomaticModel,
    defaultValue: AutomaticModel.ModelAndLabelBitmap,
  }),
  createStringColumn({ name: 'CustomData', maxLength: 10_000 }),
  createStringColumn({ name: 'DBGUID', maxLength: 36 }),
  createIntegerColumn({
    name: 'Source',
    min: -FOUR_NINES,
    max: FOUR_NINES,
    defaultValue: 0,
  }),
  createIntegerColumn({
    name: 'TechnicalKey',
    min: -1,
    max: 2_147_483_647,
    defaultValue: -1,
  }),
  createFixedValueColumn({ name: 'Squeeze/expandUnitsOnly', value: 0 }),
];

export type PsaProduct = PsaDefinition<typeof productColumns>;
export const toPsaProduct = (data: PsaProduct) =>
  toPsaRow(data, productColumns);
