/* eslint-disable perfectionist/sort-objects -- keys follow the ProSpace data-file column order, which is what the file is */
import { Schema as S } from 'effect';

import {
  CodeFromPsaCell,
  FlagFromPsaCell,
  NumberFromPsaCell,
  TextFromPsaCell,
} from './psa-cells';
import {
  PsaAutomaticModelOrDefaultFromCode,
  PsaMerchandisingDirectionOrDefaultFromCode,
  PsaMerchandisingNumberOrDefaultFromCode,
  PsaMerchandisingPlacementOrDefaultFromCode,
  PsaMerchandisingSizeOrDefaultFromCode,
  PsaMerchandisingSqueezeFromCode,
  PsaMerchandisingStyleFromCode,
  PsaOrientationFromCode,
} from './psa-code-lists';
import {
  PsaRecordFromPsaRowFor,
  PsaUnknownRow,
  type PsaRowDefaults,
} from './psa-rows';

export const PSA_POSITION_DEFAULTS: PsaRowDefaults<PsaPosition> = {
  upc: '',
  id: '',
  key: '',
  x: 0,
  width: 0,
  y: 0,
  height: 0,
  z: 0,
  depth: 0,
  slope: 0,
  angle: 0,
  roll: 0,
  merch_style: 'unit',
  h_facings: 1,
  v_facings: 1,
  d_facings: 1,
  x_cap_num: 0,
  x_cap_nested: false,
  x_cap_reversed: false,
  x_cap_orientation: 'side',
  y_cap_num: 0,
  y_cap_nested: false,
  y_cap_reversed: false,
  y_cap_orientation: 'top',
  z_cap_num: 0,
  z_cap_nested: false,
  z_cap_reversed: true,
  z_cap_orientation: 'side',
  orientation: 'front',
  jumble_width: 0,
  jumble_height: 0,
  jumble_depth: 0,
  merch_style_width: 0,
  merch_style_height: 0,
  merch_style_depth: 0,
  full_width: 0,
  full_height: 0,
  full_depth: 0,
  x_sub_units: 0,
  y_sub_units: 0,
  z_sub_units: 0,
  peg_id: '',
  manual_units: 1,
  rank_x: 1,
  rank_y: 1,
  rank_z: 1,
  peg_span: 0,
  always_float: false,
  primary_position_label_format_name: '',
  secondary_position_label_format_name: '',
  merch_x_min: -1,
  merch_x_max: -1,
  merch_x_uprights: -1,
  merch_x_caps: -1,
  merch_x_placement: 'default',
  merch_x_number: 'default',
  merch_x_size: 'default',
  merch_x_direction: 'default',
  merch_x_squeeze: 'default',
  merch_y_min: -1,
  merch_y_max: -1,
  merch_y_uprights: -1,
  merch_y_caps: -1,
  merch_y_placement: 'default',
  merch_y_number: 'default',
  merch_y_size: 'default',
  merch_y_direction: 'default',
  merch_y_squeeze: 'default',
  merch_z_min: -1,
  merch_z_max: -1,
  merch_z_uprights: -1,
  merch_z_caps: -1,
  merch_z_placement: 'default',
  merch_z_number: 'default',
  merch_z_size: 'default',
  merch_z_direction: 'default',
  merch_z_squeeze: 'default',
  desc_1: '',
  desc_2: '',
  desc_3: '',
  desc_4: '',
  desc_5: '',
  desc_6: '',
  desc_7: '',
  desc_8: '',
  desc_9: '',
  desc_10: '',
  desc_11: '',
  desc_12: '',
  desc_13: '',
  desc_14: '',
  desc_15: '',
  desc_16: '',
  desc_17: '',
  desc_18: '',
  desc_19: '',
  desc_20: '',
  desc_21: '',
  desc_22: '',
  desc_23: '',
  desc_24: '',
  desc_25: '',
  desc_26: '',
  desc_27: '',
  desc_28: '',
  desc_29: '',
  desc_30: '',
  value_1: 0,
  value_2: 0,
  value_3: 0,
  value_4: 0,
  value_5: 0,
  value_6: 0,
  value_7: 0,
  value_8: 0,
  value_9: 0,
  value_10: 0,
  value_11: 0,
  value_12: 0,
  value_13: 0,
  value_14: 0,
  value_15: 0,
  value_16: 0,
  value_17: 0,
  value_18: 0,
  value_19: 0,
  value_20: 0,
  value_21: 0,
  value_22: 0,
  value_23: 0,
  value_24: 0,
  value_25: 0,
  value_26: 0,
  value_27: 0,
  value_28: 0,
  value_29: 0,
  value_30: 0,
  flag_1: false,
  flag_2: false,
  flag_3: false,
  flag_4: false,
  flag_5: false,
  flag_6: false,
  flag_7: false,
  flag_8: false,
  flag_9: false,
  flag_10: false,
  use_target_space_x: false,
  use_target_space_y: false,
  use_target_space_z: false,
  target_space_x: 0,
  target_space_y: 0,
  target_space_z: 0,
  location_id: -1,
  changed: false,
  replenishment_min: 0,
  replenishment_max: 0,
  shape_id: '',
  bitmap_id_override: '',
  hide_if_printing: false,
  part_id: '',
  bitmap_id_override_unit: false,
  automatic_model: 'default',
  x_cap_with_units: false,
  y_cap_with_units: false,
  z_cap_with_units: false,
};

export const PsaPosition = S.TaggedStruct('Position', {
  upc: TextFromPsaCell,
  id: TextFromPsaCell,
  key: TextFromPsaCell,
  x: NumberFromPsaCell,
  width: NumberFromPsaCell,
  y: NumberFromPsaCell,
  height: NumberFromPsaCell,
  z: NumberFromPsaCell,
  depth: NumberFromPsaCell,
  slope: NumberFromPsaCell,
  angle: NumberFromPsaCell,
  roll: NumberFromPsaCell,
  merch_style: CodeFromPsaCell(PsaMerchandisingStyleFromCode),
  h_facings: NumberFromPsaCell,
  v_facings: NumberFromPsaCell,
  d_facings: NumberFromPsaCell,
  x_cap_num: NumberFromPsaCell,
  x_cap_nested: FlagFromPsaCell,
  x_cap_reversed: FlagFromPsaCell,
  x_cap_orientation: CodeFromPsaCell(PsaOrientationFromCode),
  y_cap_num: NumberFromPsaCell,
  y_cap_nested: FlagFromPsaCell,
  y_cap_reversed: FlagFromPsaCell,
  y_cap_orientation: CodeFromPsaCell(PsaOrientationFromCode),
  z_cap_num: NumberFromPsaCell,
  z_cap_nested: FlagFromPsaCell,
  z_cap_reversed: FlagFromPsaCell,
  z_cap_orientation: CodeFromPsaCell(PsaOrientationFromCode),
  orientation: CodeFromPsaCell(PsaOrientationFromCode),
  jumble_width: NumberFromPsaCell,
  jumble_height: NumberFromPsaCell,
  jumble_depth: NumberFromPsaCell,
  merch_style_width: NumberFromPsaCell,
  merch_style_height: NumberFromPsaCell,
  merch_style_depth: NumberFromPsaCell,
  full_width: NumberFromPsaCell,
  full_height: NumberFromPsaCell,
  full_depth: NumberFromPsaCell,
  x_sub_units: NumberFromPsaCell,
  y_sub_units: NumberFromPsaCell,
  z_sub_units: NumberFromPsaCell,
  peg_id: TextFromPsaCell,
  manual_units: NumberFromPsaCell,
  rank_x: NumberFromPsaCell,
  rank_y: NumberFromPsaCell,
  rank_z: NumberFromPsaCell,
  peg_span: NumberFromPsaCell,
  always_float: FlagFromPsaCell,
  primary_position_label_format_name: TextFromPsaCell,
  secondary_position_label_format_name: TextFromPsaCell,
  merch_x_min: NumberFromPsaCell,
  merch_x_max: NumberFromPsaCell,
  merch_x_uprights: NumberFromPsaCell,
  merch_x_caps: NumberFromPsaCell,
  merch_x_placement: CodeFromPsaCell(
    PsaMerchandisingPlacementOrDefaultFromCode,
  ),
  merch_x_number: CodeFromPsaCell(PsaMerchandisingNumberOrDefaultFromCode),
  merch_x_size: CodeFromPsaCell(PsaMerchandisingSizeOrDefaultFromCode),
  merch_x_direction: CodeFromPsaCell(
    PsaMerchandisingDirectionOrDefaultFromCode,
  ),
  merch_x_squeeze: CodeFromPsaCell(PsaMerchandisingSqueezeFromCode),
  merch_y_min: NumberFromPsaCell,
  merch_y_max: NumberFromPsaCell,
  merch_y_uprights: NumberFromPsaCell,
  merch_y_caps: NumberFromPsaCell,
  merch_y_placement: CodeFromPsaCell(
    PsaMerchandisingPlacementOrDefaultFromCode,
  ),
  merch_y_number: CodeFromPsaCell(PsaMerchandisingNumberOrDefaultFromCode),
  merch_y_size: CodeFromPsaCell(PsaMerchandisingSizeOrDefaultFromCode),
  merch_y_direction: CodeFromPsaCell(
    PsaMerchandisingDirectionOrDefaultFromCode,
  ),
  merch_y_squeeze: CodeFromPsaCell(PsaMerchandisingSqueezeFromCode),
  merch_z_min: NumberFromPsaCell,
  merch_z_max: NumberFromPsaCell,
  merch_z_uprights: NumberFromPsaCell,
  merch_z_caps: NumberFromPsaCell,
  merch_z_placement: CodeFromPsaCell(
    PsaMerchandisingPlacementOrDefaultFromCode,
  ),
  merch_z_number: CodeFromPsaCell(PsaMerchandisingNumberOrDefaultFromCode),
  merch_z_size: CodeFromPsaCell(PsaMerchandisingSizeOrDefaultFromCode),
  merch_z_direction: CodeFromPsaCell(
    PsaMerchandisingDirectionOrDefaultFromCode,
  ),
  merch_z_squeeze: CodeFromPsaCell(PsaMerchandisingSqueezeFromCode),
  desc_1: TextFromPsaCell,
  desc_2: TextFromPsaCell,
  desc_3: TextFromPsaCell,
  desc_4: TextFromPsaCell,
  desc_5: TextFromPsaCell,
  desc_6: TextFromPsaCell,
  desc_7: TextFromPsaCell,
  desc_8: TextFromPsaCell,
  desc_9: TextFromPsaCell,
  desc_10: TextFromPsaCell,
  desc_11: TextFromPsaCell,
  desc_12: TextFromPsaCell,
  desc_13: TextFromPsaCell,
  desc_14: TextFromPsaCell,
  desc_15: TextFromPsaCell,
  desc_16: TextFromPsaCell,
  desc_17: TextFromPsaCell,
  desc_18: TextFromPsaCell,
  desc_19: TextFromPsaCell,
  desc_20: TextFromPsaCell,
  desc_21: TextFromPsaCell,
  desc_22: TextFromPsaCell,
  desc_23: TextFromPsaCell,
  desc_24: TextFromPsaCell,
  desc_25: TextFromPsaCell,
  desc_26: TextFromPsaCell,
  desc_27: TextFromPsaCell,
  desc_28: TextFromPsaCell,
  desc_29: TextFromPsaCell,
  desc_30: TextFromPsaCell,
  value_1: NumberFromPsaCell,
  value_2: NumberFromPsaCell,
  value_3: NumberFromPsaCell,
  value_4: NumberFromPsaCell,
  value_5: NumberFromPsaCell,
  value_6: NumberFromPsaCell,
  value_7: NumberFromPsaCell,
  value_8: NumberFromPsaCell,
  value_9: NumberFromPsaCell,
  value_10: NumberFromPsaCell,
  value_11: NumberFromPsaCell,
  value_12: NumberFromPsaCell,
  value_13: NumberFromPsaCell,
  value_14: NumberFromPsaCell,
  value_15: NumberFromPsaCell,
  value_16: NumberFromPsaCell,
  value_17: NumberFromPsaCell,
  value_18: NumberFromPsaCell,
  value_19: NumberFromPsaCell,
  value_20: NumberFromPsaCell,
  value_21: NumberFromPsaCell,
  value_22: NumberFromPsaCell,
  value_23: NumberFromPsaCell,
  value_24: NumberFromPsaCell,
  value_25: NumberFromPsaCell,
  value_26: NumberFromPsaCell,
  value_27: NumberFromPsaCell,
  value_28: NumberFromPsaCell,
  value_29: NumberFromPsaCell,
  value_30: NumberFromPsaCell,
  flag_1: FlagFromPsaCell,
  flag_2: FlagFromPsaCell,
  flag_3: FlagFromPsaCell,
  flag_4: FlagFromPsaCell,
  flag_5: FlagFromPsaCell,
  flag_6: FlagFromPsaCell,
  flag_7: FlagFromPsaCell,
  flag_8: FlagFromPsaCell,
  flag_9: FlagFromPsaCell,
  flag_10: FlagFromPsaCell,
  use_target_space_x: FlagFromPsaCell,
  use_target_space_y: FlagFromPsaCell,
  use_target_space_z: FlagFromPsaCell,
  target_space_x: NumberFromPsaCell,
  target_space_y: NumberFromPsaCell,
  target_space_z: NumberFromPsaCell,
  location_id: NumberFromPsaCell,
  changed: FlagFromPsaCell,
  replenishment_min: NumberFromPsaCell,
  replenishment_max: NumberFromPsaCell,
  shape_id: TextFromPsaCell,
  bitmap_id_override: TextFromPsaCell,
  hide_if_printing: FlagFromPsaCell,
  part_id: TextFromPsaCell,
  bitmap_id_override_unit: FlagFromPsaCell,
  automatic_model: CodeFromPsaCell(PsaAutomaticModelOrDefaultFromCode),
  x_cap_with_units: FlagFromPsaCell,
  y_cap_with_units: FlagFromPsaCell,
  z_cap_with_units: FlagFromPsaCell,
  unknownRowsAfter: S.Array(PsaUnknownRow),
}).annotations({ identifier: 'PsaPosition' });
export type PsaPosition = typeof PsaPosition.Type;

export const PsaPositionFromPsaRow = PsaRecordFromPsaRowFor(
  PsaPosition,
).annotations({
  identifier: 'PsaPositionFromPsaRow',
});
