/* eslint-disable perfectionist/sort-objects -- keys follow the ProSpace data-file column order, which is what the file is */
import { Schema as S } from 'effect';

import {
  CodeFromPsaCell,
  FlagFromPsaCell,
  NumberFromPsaCell,
  TextFromPsaCell,
} from './psa-cells';
import {
  PsaCanAttachFromCode,
  PsaCanCombineFromCode,
  PsaFillPatternFromCode,
  PsaFixtureTypeFromCode,
  PsaMerchandisingDirectionOrDefaultFromCode,
  PsaMerchandisingNumberOrDefaultFromCode,
  PsaMerchandisingPlacementOrDefaultFromCode,
  PsaMerchandisingSizeOrDefaultFromCode,
  PsaMerchandisingSqueezeFromCode,
  PsaMerchandisingStyleOrDefaultFromCode,
} from './psa-code-lists';
import {
  PsaRecordFromPsaRowFor,
  PsaUnknownRow,
  type PsaRowDefaults,
} from './psa-rows';

export const PSA_FIXTURE_DEFAULTS: PsaRowDefaults<PsaFixture> = {
  type: 'shelf',
  name: '',
  key: '',
  x: 0,
  width: 0,
  y: 0,
  height: 0,
  z: 0,
  depth: 0,
  slope: 0,
  angle: 0,
  roll: 0,
  color: 0,
  assembly: '',
  x_spacing: 0,
  y_spacing: 0,
  x_start: 0,
  y_start: 0,
  wall_width: 0,
  wall_height: 0,
  wall_depth: 0,
  curve: 0,
  merch: 0,
  check_other_fixtures: true,
  check_other_positions: true,
  can_obstruct: true,
  left_overhang: 0,
  right_overhang: 0,
  lower_overhang: 0,
  upper_overhang: 0,
  back_overhang: 0,
  front_overhang: 0,
  default_merch_style: 'default',
  divider_width: 0,
  divider_height: 0,
  divider_depth: 0,
  can_combine: 'no',
  grille_height: 0,
  notch_offset: 0,
  x_spacing_2: 0,
  x_start_2: 0,
  peg_drop: 0,
  peg_gap_x: 0,
  peg_gap_y: 0,
  primary_fixture_label_format_name: '',
  secondary_fixture_label_format_name: '',
  shape_id: '',
  bitmap_id: '',
  merch_x_min: -1,
  merch_x_max: -1,
  merch_x_uprights: -1,
  merch_x_caps: -1,
  merch_x_placement: 'default',
  merch_x_number: 'default',
  merch_x_size: 'default',
  merch_x_direction: 'default',
  merch_x_squeeze: 'default',
  merch_y_min: -1,
  merch_y_max: -1,
  merch_y_uprights: -1,
  merch_y_caps: -1,
  merch_y_placement: 'default',
  merch_y_number: 'default',
  merch_y_size: 'default',
  merch_y_direction: 'default',
  merch_y_squeeze: 'default',
  merch_z_min: -1,
  merch_z_max: -1,
  merch_z_uprights: -1,
  merch_z_caps: -1,
  merch_z_placement: 'default',
  merch_z_number: 'default',
  merch_z_size: 'default',
  merch_z_direction: 'default',
  merch_z_squeeze: 'default',
  desc_1: '',
  desc_2: '',
  desc_3: '',
  desc_4: '',
  desc_5: '',
  desc_6: '',
  desc_7: '',
  desc_8: '',
  desc_9: '',
  desc_10: '',
  desc_11: '',
  desc_12: '',
  desc_13: '',
  desc_14: '',
  desc_15: '',
  desc_16: '',
  desc_17: '',
  desc_18: '',
  desc_19: '',
  desc_20: '',
  desc_21: '',
  desc_22: '',
  desc_23: '',
  desc_24: '',
  desc_25: '',
  desc_26: '',
  desc_27: '',
  desc_28: '',
  desc_29: '',
  desc_30: '',
  value_1: 0,
  value_2: 0,
  value_3: 0,
  value_4: 0,
  value_5: 0,
  value_6: 0,
  value_7: 0,
  value_8: 0,
  value_9: 0,
  value_10: 0,
  value_11: 0,
  value_12: 0,
  value_13: 0,
  value_14: 0,
  value_15: 0,
  value_16: 0,
  value_17: 0,
  value_18: 0,
  value_19: 0,
  value_20: 0,
  value_21: 0,
  value_22: 0,
  value_23: 0,
  value_24: 0,
  value_25: 0,
  value_26: 0,
  value_27: 0,
  value_28: 0,
  value_29: 0,
  value_30: 0,
  flag_1: false,
  flag_2: false,
  flag_3: false,
  flag_4: false,
  flag_5: false,
  flag_6: false,
  flag_7: false,
  flag_8: false,
  flag_9: false,
  flag_10: false,
  location_id: -1,
  fill_pattern: 'solid',
  model_filename: '',
  weight_capacity: 0,
  changed: false,
  divider_at_start: true,
  divider_at_end: false,
  dividers_between_facings: false,
  transparency: 0,
  hide_if_printing: false,
  product_association: '',
  part_id: '',
  hide_view_dimensions: false,
  gln: '',
  can_attach: 'no',
  attached_to_fixture: '',
  is_attached: false,
  rank_x: -1,
  rank_y: -1,
  rank_z: -1,
  fixture_guid: '',
  bracket_width: 0,
  bracket_height: 0,
  bracket_depth: 0,
};

export const PsaFixture = S.TaggedStruct('Fixture', {
  type: CodeFromPsaCell(PsaFixtureTypeFromCode),
  name: TextFromPsaCell,
  key: TextFromPsaCell,
  x: NumberFromPsaCell,
  width: NumberFromPsaCell,
  y: NumberFromPsaCell,
  height: NumberFromPsaCell,
  z: NumberFromPsaCell,
  depth: NumberFromPsaCell,
  slope: NumberFromPsaCell,
  angle: NumberFromPsaCell,
  roll: NumberFromPsaCell,
  color: NumberFromPsaCell,
  assembly: TextFromPsaCell,
  x_spacing: NumberFromPsaCell,
  y_spacing: NumberFromPsaCell,
  x_start: NumberFromPsaCell,
  y_start: NumberFromPsaCell,
  wall_width: NumberFromPsaCell,
  wall_height: NumberFromPsaCell,
  wall_depth: NumberFromPsaCell,
  curve: NumberFromPsaCell,
  merch: NumberFromPsaCell,
  check_other_fixtures: FlagFromPsaCell,
  check_other_positions: FlagFromPsaCell,
  can_obstruct: FlagFromPsaCell,
  left_overhang: NumberFromPsaCell,
  right_overhang: NumberFromPsaCell,
  lower_overhang: NumberFromPsaCell,
  upper_overhang: NumberFromPsaCell,
  back_overhang: NumberFromPsaCell,
  front_overhang: NumberFromPsaCell,
  default_merch_style: CodeFromPsaCell(PsaMerchandisingStyleOrDefaultFromCode),
  divider_width: NumberFromPsaCell,
  divider_height: NumberFromPsaCell,
  divider_depth: NumberFromPsaCell,
  can_combine: CodeFromPsaCell(PsaCanCombineFromCode),
  grille_height: NumberFromPsaCell,
  notch_offset: NumberFromPsaCell,
  x_spacing_2: NumberFromPsaCell,
  x_start_2: NumberFromPsaCell,
  peg_drop: NumberFromPsaCell,
  peg_gap_x: NumberFromPsaCell,
  peg_gap_y: NumberFromPsaCell,
  primary_fixture_label_format_name: TextFromPsaCell,
  secondary_fixture_label_format_name: TextFromPsaCell,
  shape_id: TextFromPsaCell,
  bitmap_id: TextFromPsaCell,
  merch_x_min: NumberFromPsaCell,
  merch_x_max: NumberFromPsaCell,
  merch_x_uprights: NumberFromPsaCell,
  merch_x_caps: NumberFromPsaCell,
  merch_x_placement: CodeFromPsaCell(
    PsaMerchandisingPlacementOrDefaultFromCode,
  ),
  merch_x_number: CodeFromPsaCell(PsaMerchandisingNumberOrDefaultFromCode),
  merch_x_size: CodeFromPsaCell(PsaMerchandisingSizeOrDefaultFromCode),
  merch_x_direction: CodeFromPsaCell(
    PsaMerchandisingDirectionOrDefaultFromCode,
  ),
  merch_x_squeeze: CodeFromPsaCell(PsaMerchandisingSqueezeFromCode),
  merch_y_min: NumberFromPsaCell,
  merch_y_max: NumberFromPsaCell,
  merch_y_uprights: NumberFromPsaCell,
  merch_y_caps: NumberFromPsaCell,
  merch_y_placement: CodeFromPsaCell(
    PsaMerchandisingPlacementOrDefaultFromCode,
  ),
  merch_y_number: CodeFromPsaCell(PsaMerchandisingNumberOrDefaultFromCode),
  merch_y_size: CodeFromPsaCell(PsaMerchandisingSizeOrDefaultFromCode),
  merch_y_direction: CodeFromPsaCell(
    PsaMerchandisingDirectionOrDefaultFromCode,
  ),
  merch_y_squeeze: CodeFromPsaCell(PsaMerchandisingSqueezeFromCode),
  merch_z_min: NumberFromPsaCell,
  merch_z_max: NumberFromPsaCell,
  merch_z_uprights: NumberFromPsaCell,
  merch_z_caps: NumberFromPsaCell,
  merch_z_placement: CodeFromPsaCell(
    PsaMerchandisingPlacementOrDefaultFromCode,
  ),
  merch_z_number: CodeFromPsaCell(PsaMerchandisingNumberOrDefaultFromCode),
  merch_z_size: CodeFromPsaCell(PsaMerchandisingSizeOrDefaultFromCode),
  merch_z_direction: CodeFromPsaCell(
    PsaMerchandisingDirectionOrDefaultFromCode,
  ),
  merch_z_squeeze: CodeFromPsaCell(PsaMerchandisingSqueezeFromCode),
  desc_1: TextFromPsaCell,
  desc_2: TextFromPsaCell,
  desc_3: TextFromPsaCell,
  desc_4: TextFromPsaCell,
  desc_5: TextFromPsaCell,
  desc_6: TextFromPsaCell,
  desc_7: TextFromPsaCell,
  desc_8: TextFromPsaCell,
  desc_9: TextFromPsaCell,
  desc_10: TextFromPsaCell,
  desc_11: TextFromPsaCell,
  desc_12: TextFromPsaCell,
  desc_13: TextFromPsaCell,
  desc_14: TextFromPsaCell,
  desc_15: TextFromPsaCell,
  desc_16: TextFromPsaCell,
  desc_17: TextFromPsaCell,
  desc_18: TextFromPsaCell,
  desc_19: TextFromPsaCell,
  desc_20: TextFromPsaCell,
  desc_21: TextFromPsaCell,
  desc_22: TextFromPsaCell,
  desc_23: TextFromPsaCell,
  desc_24: TextFromPsaCell,
  desc_25: TextFromPsaCell,
  desc_26: TextFromPsaCell,
  desc_27: TextFromPsaCell,
  desc_28: TextFromPsaCell,
  desc_29: TextFromPsaCell,
  desc_30: TextFromPsaCell,
  value_1: NumberFromPsaCell,
  value_2: NumberFromPsaCell,
  value_3: NumberFromPsaCell,
  value_4: NumberFromPsaCell,
  value_5: NumberFromPsaCell,
  value_6: NumberFromPsaCell,
  value_7: NumberFromPsaCell,
  value_8: NumberFromPsaCell,
  value_9: NumberFromPsaCell,
  value_10: NumberFromPsaCell,
  value_11: NumberFromPsaCell,
  value_12: NumberFromPsaCell,
  value_13: NumberFromPsaCell,
  value_14: NumberFromPsaCell,
  value_15: NumberFromPsaCell,
  value_16: NumberFromPsaCell,
  value_17: NumberFromPsaCell,
  value_18: NumberFromPsaCell,
  value_19: NumberFromPsaCell,
  value_20: NumberFromPsaCell,
  value_21: NumberFromPsaCell,
  value_22: NumberFromPsaCell,
  value_23: NumberFromPsaCell,
  value_24: NumberFromPsaCell,
  value_25: NumberFromPsaCell,
  value_26: NumberFromPsaCell,
  value_27: NumberFromPsaCell,
  value_28: NumberFromPsaCell,
  value_29: NumberFromPsaCell,
  value_30: NumberFromPsaCell,
  flag_1: FlagFromPsaCell,
  flag_2: FlagFromPsaCell,
  flag_3: FlagFromPsaCell,
  flag_4: FlagFromPsaCell,
  flag_5: FlagFromPsaCell,
  flag_6: FlagFromPsaCell,
  flag_7: FlagFromPsaCell,
  flag_8: FlagFromPsaCell,
  flag_9: FlagFromPsaCell,
  flag_10: FlagFromPsaCell,
  location_id: NumberFromPsaCell,
  fill_pattern: CodeFromPsaCell(PsaFillPatternFromCode),
  model_filename: TextFromPsaCell,
  weight_capacity: NumberFromPsaCell,
  changed: FlagFromPsaCell,
  divider_at_start: FlagFromPsaCell,
  divider_at_end: FlagFromPsaCell,
  dividers_between_facings: FlagFromPsaCell,
  transparency: NumberFromPsaCell,
  hide_if_printing: FlagFromPsaCell,
  product_association: TextFromPsaCell,
  part_id: TextFromPsaCell,
  hide_view_dimensions: FlagFromPsaCell,
  gln: TextFromPsaCell,
  can_attach: CodeFromPsaCell(PsaCanAttachFromCode),
  attached_to_fixture: TextFromPsaCell,
  is_attached: FlagFromPsaCell,
  rank_x: NumberFromPsaCell,
  rank_y: NumberFromPsaCell,
  rank_z: NumberFromPsaCell,
  fixture_guid: TextFromPsaCell,
  bracket_width: NumberFromPsaCell,
  bracket_height: NumberFromPsaCell,
  bracket_depth: NumberFromPsaCell,
  unknownRowsAfter: S.Array(PsaUnknownRow),
}).annotate({ identifier: 'PsaFixture' });
export type PsaFixture = typeof PsaFixture.Type;

export const PsaFixtureFromPsaRow = PsaRecordFromPsaRowFor(PsaFixture).annotate(
  {
    identifier: 'PsaFixtureFromPsaRow',
  },
);

/** A record with every column empty, which a new row is spread from. */
export const PSA_EMPTY_FIXTURE: PsaFixture = S.decodeSync(PsaFixtureFromPsaRow)(
  {
    _tag: 'Fixture',
    cells: [],
    unknownRowsAfter: [],
  },
);
