/* eslint-disable perfectionist/sort-objects -- keys follow the ProSpace data-file column order, which is what the file is */
import { Schema as S } from 'effect';

import {
  CodeFromPsaCell,
  FlagFromPsaCell,
  NumberFromPsaCell,
  TextFromPsaCell,
} from './psa-cells';
import {
  PsaDoorDirectionFromCode,
  PsaFillPatternFromCode,
} from './psa-code-lists';
import {
  PsaRecordFromPsaRowFor,
  PsaUnknownRow,
  type PsaRowDefaults,
} from './psa-rows';

export const PSA_SEGMENT_DEFAULTS: PsaRowDefaults<PsaSegment> = {
  name: '',
  key: '',
  x: 0,
  width: 0,
  y: 0,
  height: 0,
  z: 0,
  depth: 0,
  angle: 0,
  offset_x: 0,
  offset_y: 0,
  door: false,
  door_direction: 'left',
  desc_1: '',
  desc_2: '',
  desc_3: '',
  desc_4: '',
  desc_5: '',
  desc_6: '',
  desc_7: '',
  desc_8: '',
  desc_9: '',
  desc_10: '',
  value_1: 0,
  value_2: 0,
  value_3: 0,
  value_4: 0,
  value_5: 0,
  value_6: 0,
  value_7: 0,
  value_8: 0,
  value_9: 0,
  value_10: 0,
  flag_1: false,
  flag_2: false,
  flag_3: false,
  flag_4: false,
  flag_5: false,
  flag_6: false,
  flag_7: false,
  flag_8: false,
  flag_9: false,
  flag_10: false,
  frame_width: 0,
  frame_height: 0,
  changed: false,
  frame_color: -1,
  frame_fill_pattern: 'solid',
  part_id: '',
  gln: '',
  can_separate: true,
};

export const PsaSegment = S.TaggedStruct('Segment', {
  name: TextFromPsaCell,
  key: TextFromPsaCell,
  x: NumberFromPsaCell,
  width: NumberFromPsaCell,
  y: NumberFromPsaCell,
  height: NumberFromPsaCell,
  z: NumberFromPsaCell,
  depth: NumberFromPsaCell,
  angle: NumberFromPsaCell,
  offset_x: NumberFromPsaCell,
  offset_y: NumberFromPsaCell,
  door: FlagFromPsaCell,
  door_direction: CodeFromPsaCell(PsaDoorDirectionFromCode),
  desc_1: TextFromPsaCell,
  desc_2: TextFromPsaCell,
  desc_3: TextFromPsaCell,
  desc_4: TextFromPsaCell,
  desc_5: TextFromPsaCell,
  desc_6: TextFromPsaCell,
  desc_7: TextFromPsaCell,
  desc_8: TextFromPsaCell,
  desc_9: TextFromPsaCell,
  desc_10: TextFromPsaCell,
  value_1: NumberFromPsaCell,
  value_2: NumberFromPsaCell,
  value_3: NumberFromPsaCell,
  value_4: NumberFromPsaCell,
  value_5: NumberFromPsaCell,
  value_6: NumberFromPsaCell,
  value_7: NumberFromPsaCell,
  value_8: NumberFromPsaCell,
  value_9: NumberFromPsaCell,
  value_10: NumberFromPsaCell,
  flag_1: FlagFromPsaCell,
  flag_2: FlagFromPsaCell,
  flag_3: FlagFromPsaCell,
  flag_4: FlagFromPsaCell,
  flag_5: FlagFromPsaCell,
  flag_6: FlagFromPsaCell,
  flag_7: FlagFromPsaCell,
  flag_8: FlagFromPsaCell,
  flag_9: FlagFromPsaCell,
  flag_10: FlagFromPsaCell,
  frame_width: NumberFromPsaCell,
  frame_height: NumberFromPsaCell,
  changed: FlagFromPsaCell,
  frame_color: NumberFromPsaCell,
  frame_fill_pattern: CodeFromPsaCell(PsaFillPatternFromCode),
  part_id: TextFromPsaCell,
  gln: TextFromPsaCell,
  can_separate: FlagFromPsaCell,
  unknownRowsAfter: S.Array(PsaUnknownRow),
}).annotate({ identifier: 'PsaSegment' });
export type PsaSegment = typeof PsaSegment.Type;

export const PsaSegmentFromPsaRow = PsaRecordFromPsaRowFor(PsaSegment).annotate(
  {
    identifier: 'PsaSegmentFromPsaRow',
  },
);

/** A record with every column empty, which a new row is spread from. */
export const PSA_EMPTY_SEGMENT: PsaSegment = S.decodeSync(PsaSegmentFromPsaRow)(
  {
    _tag: 'Segment',
    cells: [],
    unknownRowsAfter: [],
  },
);
